#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 0

bspc config normal_border_color "#222222"
bspc config focused_border_color "#222222"

bspc config window_gap 	5

bspc config split_ratio 0

bspc config focus_follows_pointer true
bspc config point_follows_focus true

exec feh --bg-fill /home/vee/.config/bspwm/ghibli.jpg &
exec xrdb -merge .Xresources &
exec polybar &

sleep 1

~/.config/bspwm/scripts/2bspwm.sh
