#!/bin/sh

super + Return
	urxvt

super + q
	bspc node -c

super + shift + e
	pkill -15 Xorg && clear

super + Escape
	pkill -USR1 -x sxhkd

super + shift + r
	~/.config/bspwm/bspwmrc

super + d
	dmenu_run -fn TerminessNerdFont:regular:pixelsize=19 -nb '#1f1f20' -nf '#c1b58b' -sb '#ac895a' -sf '#453637' -p "exec" -b

super + {1-9,0}
	bspc desktop -f '^{1,2,3,4,5,6,7,8,9,10}'

super + {_,shift +} {1-9,0}
	bspc {desktop -f,node -d} '^{1,2,3,4,5,6,7,8,9,10}'

super + space
	bspc node -t '~fullscreen' && bspc node "polybar" -g hidden=on

super + shift + s
	scrot

super + {h,j,k,l}
  bspc node -z {left -20 0 || bspc node -z right -20 0, \
                bottom 0 20 || bspc node -z top 0 20,\
                top 0 -20 || bspc node -z bottom 0 -20,\
                right 20 0 || bspc node -z left 20 0}

super + shift + {h,j,k,l}
 bspc node -z {right -20 0 || bspc node -z left -20 0, \
 	       top 0 20 || bspc node - bottom 0 20,\
 	       bottom 0 -20 || bspc node -z top 0 -20,\
 	       left 20 0 || bspc node -z right 20 0}

alt + {_,shift + }{h,j,k,l}
	bspc node --{focus,swap} {west,south,north,east}

super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

super + b
	bspc rule -a '*' -o  state=floating size=100x50
